FROM java:8

MAINTAINER sawan darekar <sawan.darekar@tomtom.com>

COPY docker-spring-boot-0.0.1-SNAPSHOT.jar /usr/local/docker-spring-boot.jar
ENTRYPOINT ["java","-jar","/usr/local/docker-spring-boot.jar"]
